<?php

namespace AppBundle\Repository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getBookedRooms()
    {
        $em = $this->getEntityManager();

        $RAW_QUERY = 'SELECT client.title, client.name, client.last_name,
                             reservation.id AS reservation_id, reservation.room_id, reservation.date_in, reservation.date_out,
                             room.name AS room_name
                FROM client 
                INNER JOIN reservation ON client.id=reservation.client_id
                INNER JOIN room ON room.id=reservation.room_id;';

        $statement = $em->getConnection()->prepare($RAW_QUERY);
        $statement->execute();

        $result = $statement->fetchAll();
        dump($result);
        return $result;

    }


}
